services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      fastapi:
        condition: service_started

  fastapi:
    build: ./fastapi
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:16

    env_file:
      - ./postgres/.env

    expose:
      - "5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  pgadmin:
    image: dpage/pgadmin4

    env_file:
      - ./pgadmin/.env  
    ports:
      - "5051:80"

volumes:
  postgres_data:
