services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      fastapi:
        condition: service_started

  fastapi:
    build: ./fastapi
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy

  cronjob:
    build: ./cronjob
    env_file:
      - ./cronjob/.env
      - ./db/.env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16

    env_file:
      - ./db/.env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    expose:
      - "5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4

    env_file:
      - ./db/.env

    ports:
      - "5051:80"

volumes:
  postgres_data:
